"""
Stage 3 — Retrieval-Grounded Chain-of-Thought (RG-CoT)

Interleaves LLM reasoning step generation with source-based verification.
Each step is:
    1. Generated by the LLM using prior steps + retrieved context.
    2. Verified against retrieved sources via a dedicated verification call.
    3. If contradicted, regenerated with corrective context injected.
"""

from __future__ import annotations

import json
import re
from typing import Callable, List

from loguru import logger

from pecar.models import (
    LearnerProfile,
    ReasoningStep,
    VerificationResult,
    VerificationStatus,
)
from pecar import prompts


class RetrievalGroundedCoT:
    """
    Stage 3 — Retrieval-Grounded Chain-of-Thought (RG-CoT).

    Prevents hallucination propagation by verifying each reasoning step
    against retrieved sources before proceeding.
    """

    def __init__(self, call_llm_fn: Callable, max_regeneration_attempts: int = 2) -> None:
        """
        Args:
            call_llm_fn: Async callable matching the signature:
                         async (prompt: str, system: str, **kwargs) -> str
            max_regeneration_attempts: Max retries per step if contradicted.
        """
        self._llm = call_llm_fn
        self.max_regen = max_regeneration_attempts

    async def generate_and_verify_steps(
        self,
        query: str,
        retrieved_context: str,
        sources: List[str],
        num_steps: int,
        system_prompt: str,
        learner: LearnerProfile,
    ) -> List[ReasoningStep]:
        """
        Generate ``num_steps`` reasoning steps with inline verification.
        """
        completed_steps: List[ReasoningStep] = []

        for step_num in range(1, num_steps + 1):
            step = await self._generate_step(
                step_num=step_num,
                query=query,
                retrieved_context=retrieved_context,
                completed_steps=completed_steps,
                system_prompt=system_prompt,
            )

            verification = await self._verify_step(step, sources, retrieved_context)
            step.verification_status = verification.status
            step.confidence = max(0.0, min(1.0, step.confidence + verification.confidence_delta))
            step.supporting_sources = [s for s in sources if verification.supporting_excerpt and s]

            if verification.status == VerificationStatus.CONTRADICTED:
                step = await self._handle_contradiction(
                    step=step,
                    verification=verification,
                    completed_steps=completed_steps,
                    system_prompt=system_prompt,
                )

            completed_steps.append(step)
            logger.debug(
                "RG-CoT step %d/%d: status=%s, confidence=%.2f",
                step_num,
                num_steps,
                step.verification_status,
                step.confidence,
            )

        return completed_steps

    async def _generate_step(
        self,
        step_num: int,
        query: str,
        retrieved_context: str,
        completed_steps: List[ReasoningStep],
        system_prompt: str,
    ) -> ReasoningStep:
        """Generate a single reasoning step using prior steps as context."""
        previous_text = "\n".join(
            f"Step {s.index}: {s.content}" for s in completed_steps
        ) or "None yet."

        prompt = prompts.RG_COT_STEP.format(
            previous_steps=previous_text,
            retrieved_context=retrieved_context[:3000],
            step_num=step_num,
        )
        content = await self._llm(prompt=prompt, system=system_prompt)
        content = re.sub(r"^Step\s+\d+:\s*", "", content.strip())

        return ReasoningStep(
            index=step_num,
            content=content,
            verification_status=VerificationStatus.PENDING,
            confidence=1.0,
        )

    async def _verify_step(
        self,
        step: ReasoningStep,
        sources: List[str],
        retrieved_context: str,
    ) -> VerificationResult:
        """Ask the LLM to verify a step against retrieved sources."""
        sources_text = retrieved_context[:2000] if retrieved_context else "No sources available."

        prompt = prompts.RG_COT_VERIFY.format(
            step_content=step.content,
            sources=sources_text,
        )

        try:
            raw = await self._llm(
                prompt=prompt,
                system="You are a factual verification assistant. Respond only in valid JSON.",
            )
            json_match = re.search(r"\{.*\}", raw, re.DOTALL)
            if not json_match:
                raise ValueError("No JSON found in verification response")

            data = json.loads(json_match.group())

            status_str = data.get("status", "unverifiable")
            try:
                status = VerificationStatus(status_str)
            except ValueError:
                status = VerificationStatus.UNVERIFIABLE

            return VerificationResult(
                step_index=step.index,
                status=status,
                supporting_excerpt=data.get("supporting_excerpt"),
                contradicting_source=data.get("contradicting_source"),
                corrective_context=data.get("corrective_context"),
                confidence_delta=float(data.get("confidence_delta", 0.0)),
            )
        except Exception as exc:
            logger.warning("Verification parse error for step %d: %s", step.index, exc)
            return VerificationResult(
                step_index=step.index,
                status=VerificationStatus.UNVERIFIABLE,
                confidence_delta=0.0,
            )

    async def _handle_contradiction(
        self,
        step: ReasoningStep,
        verification: VerificationResult,
        completed_steps: List[ReasoningStep],
        system_prompt: str,
    ) -> ReasoningStep:
        """Regenerate a contradicted step, injecting corrective context."""
        corrective = verification.corrective_context or "No specific correction available."

        for attempt in range(self.max_regen):
            prompt = prompts.RG_COT_REGENERATE.format(
                original_step=step.content,
                corrective_context=corrective,
                step_num=step.index,
            )
            try:
                new_content = await self._llm(prompt=prompt, system=system_prompt)
                new_content = re.sub(r"^(Corrected\s+)?Step\s+\d+:\s*", "", new_content.strip())

                step.content = new_content
                step.corrective_context = corrective
                step.regenerated = True
                step.verification_status = VerificationStatus.VERIFIED
                step.confidence = max(0.0, min(1.0, step.confidence + 0.1))
                logger.debug("RG-CoT step %d regenerated (attempt %d)", step.index, attempt + 1)
                return step
            except Exception as exc:
                logger.warning("Regeneration attempt %d failed: %s", attempt + 1, exc)

        step.verification_status = VerificationStatus.UNVERIFIABLE
        return step
